In [7]:
# 現在兩張表都有「店家編號」，所以可以使用它當作合併依據。
### 使用店家編號合併兩張資料表
result = orders.merge(
    shops,
    on="店家編號"
)
result

   訂單編號 店家編號   金額   店家名稱  類別
0  A001  S01  180   阿明便當  便當
1  A002  S02  320  珍珠奶茶店  飲料
2  A003  S01  250   阿明便當  便當
3  A004  S03  450  老王牛肉麵  麵食

### how：決定怎麼合併

merge() 有一個`how`參數，用來決定「如果兩張表的資料沒有完全對得上，要留下哪些資料？」

常見有四種：

| `how`     | 意義                 |
| --------- | -------------------- |
| `"inner"` | 只保留兩邊都有的資料 |
| `"left"`  | 左表全部保留         |
| `"right"` | 右表全部保留         |
| `"outer"` | 左右兩邊全部保留     |

In [10]:
### 建立訂單資料
orders = pd.DataFrame({
    "店家編號": ["S01", "S02", "S03"],
    "餐點": ["雞排", "珍珠奶茶", "牛肉麵"]
})

### 建立店家資料
shops = pd.DataFrame({
    "店家編號": ["S01", "S02", "S04"],
    "店名": ["豪大雞排", "珍煮丹", "早餐店"]
})

In [12]:
# inner：只留下兩邊都有的
result = orders.merge(
    shops,
    on="店家編號",
    how="inner"
)
result

  店家編號    餐點    店名
0  S01    雞排  豪大雞排
1  S02  珍珠奶茶   珍煮丹

In [14]:
# left：左表全部留下
result = orders.merge(
    shops,
    on="店家編號",
    how="left"
)
result

  店家編號    餐點    店名
0  S01    雞排  豪大雞排
1  S02  珍珠奶茶   珍煮丹
2  S03   牛肉麵   NaN

In [15]:
# outer：兩邊全部留下
result = orders.merge(
    shops,
    on="店家編號",
    how="outer"
)
result

  店家編號    餐點    店名
0  S01    雞排  豪大雞排
1  S02  珍珠奶茶   珍煮丹
2  S03   牛肉麵   NaN
3  S04   NaN   早餐店

<!-- inner：只留下兩邊都有的 -->