小明正在準備升學，希望了解臺灣各大專校院的科系分布。請從政府資料開放平臺取得大專校院科系資料，使用 Pandas 整理資料，找出特定縣市、特定科系以及學生人數較多的科系，最後輸出分析結果。

- 資料集名稱：[大專校院各校科系別概況](https://data.gov.tw/dataset/9621)

### 下載資料

In [2]:
import requests
import pandas as pd

### 設定 CSV 網址
# url = "這裡貼上政府資料開放平臺的 CSV 下載網址"
url = "https://stats.moe.gov.tw/files/opendata/sdata.csv"

headers = {
    "User-Agent": "Mozilla/5.0"
}


### 下載 CSV
response = requests.get(
    url,
    headers=headers,
    timeout=30
)

response.raise_for_status() # 如果請求失敗 (4xx、5xx)，直接拋出例外
print("狀態碼：", response.status_code)

### 儲存 CSV
with open("../pandas_datasets/大專院科系資料.csv", "wb") as file:
    file.write(response.content)

print("CSV 下載完成")

狀態碼： 200
CSV 下載完成

### 使用 Pandas 讀取 CSV

In [3]:
df = pd.read_csv("../pandas_datasets/大專院科系資料.csv")

### 查看前 5 筆資料
df.head()

,學年度,學校代碼,學校名稱,科系代碼,科系名稱,日間∕進修別,等級別,學生數,教師數,上學年度畢業生數,縣市名稱,體系別
0,103,1,國立政治大學,140101,教育學系,D 日,D 博士,93,0,16,30 臺北市,1 一般
1,103,1,國立政治大學,140101,教育學系,D 日,M 碩士,34,0,10,30 臺北市,1 一般
2,103,1,國立政治大學,140101,教育學系,D 日,B 學士,250,17,55,30 臺北市,1 一般
3,103,1,國立政治大學,140203,華語(文)教學學系,D 日,D 博士,18,0,1,30 臺北市,1 一般
4,103,1,國立政治大學,140203,華語(文)教學學系,D 日,M 碩士,55,0,5,30 臺北市,1 一般

### 查看csv基本資料

In [4]:
### 查看資料大小
df.shape

(118000, 12)

In [5]:
### 查看欄位
df.columns

Index(['學年度', '學校代碼', '學校名稱', '科系代碼', '科系名稱', '日間∕進修別', '等級別', '學生數', '教師數',
       '上學年度畢業生數', '縣市名稱', '體系別'],
      dtype='str')

In [6]:
### 查看資料型態
df.dtypes

學年度         int64
學校代碼        int64
學校名稱          str
科系代碼          str
科系名稱          str
日間∕進修別        str
等級別           str
學生數           str
教師數         int64
上學年度畢業生數    int64
縣市名稱          str
體系別           str
dtype: object

In [7]:
### 查看完整資訊
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 118000 entries, 0 to 117999
Data columns (total 12 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   學年度       118000 non-null  int64
 1   學校代碼      118000 non-null  int64
 2   學校名稱      118000 non-null  str
 3   科系代碼      118000 non-null  str
 4   科系名稱      118000 non-null  str
 5   日間∕進修別    117912 non-null  str
 6   等級別       112433 non-null  str
 7   學生數       118000 non-null  str
 8   教師數       118000 non-null  int64
 9   上學年度畢業生數  118000 non-null  int64
 10  縣市名稱      117932 non-null  str
 11  體系別       118000 non-null  str
dtypes: int64(4), str(8)
memory usage: 10.8 MB

### 檢查缺失值與重複值

In [20]:
print("\n缺失值：", df.isna().sum())
print("-"*40)
print(df.duplicated().sum())

### 移除完全重複的資料
df = df.drop_duplicates()

df

缺失值： 學年度            0
學校代碼           0
學校名稱           0
科系代碼           0
科系名稱           0
日間∕進修別        88
等級別         5567
學生數            0
教師數            0
上學年度畢業生數       0
縣市名稱          68
體系別            0
dtype: int64
----------------------------------------
0

,學年度,學校代碼,學校名稱,科系代碼,科系名稱,日間∕進修別,等級別,學生數,教師數,上學年度畢業生數,縣市名稱,體系別
0,103,1,國立政治大學,140101,教育學系,D 日,D 博士,93,0,16,30 臺北市,1 一般
1,103,1,國立政治大學,140101,教育學系,D 日,M 碩士,34,0,10,30 臺北市,1 一般
2,103,1,國立政治大學,140101,教育學系,D 日,B 學士,250,17,55,30 臺北市,1 一般
3,103,1,國立政治大學,140203,華語(文)教學學系,D 日,D 博士,18,0,1,30 臺北市,1 一般
4,103,1,國立政治大學,140203,華語(文)教學學系,D 日,M 碩士,55,0,5,30 臺北市,1 一般
...,...,...,...,...,...,...,...,...,...,...,...,...
117995,114,3002,臺北市立大學,10152050,休閒運動管理學系,D 日,M 碩士,33,0,15,30 臺北市,1 一般
117996,114,3002,臺北市立大學,10152050,休閒運動管理學系,N 職,M 碩士,58,0,15,30 臺北市,1 一般
117997,114,3002,臺北市立大學,10152050,休閒運動管理學系,D 日,B 學士,223,9,58,30 臺北市,1 一般
117998,114,3002,臺北市立大學,99999Z01,通識及共同科目,D 日,NaN,0,7,0,30 臺北市,1 一般
117999,114,3002,臺北市立大學,99999Z05,師資培育中心,D 日,NaN,0,5,0,30 臺北市,1 一般

### 找出高雄市所有科系

In [ ]:
kaohsiung = df.loc[
    df["縣市名稱"] == "50 高雄市",
    [
        "學校名稱",
        "科系名稱",
        "學生數",
        "教師數"
    ]
]

print("\n高雄市大專校院科系：")
kaohsiung

高雄市大專校院科系：

              學校名稱         科系名稱   學生數  教師數
1338        國立中山大學         教育學系    53    0
1339        國立中山大學         教育學系    40    7
1340        國立中山大學         教育學系    49    0
1341        國立中山大學         音樂學系    50    0
1342        國立中山大學         音樂學系   161   14
...            ...          ...   ...  ...
117482      文藻外語大學         語言中心     0    6
117885  育英醫護管理專科學校          護理科  1012   35
117886  育英醫護管理專科學校  老人健康服務事業管理科   272   10
117887  育英醫護管理專科學校    化妝品應用與管理科   211    7
117888  育英醫護管理專科學校      通識及共同科目     0    4

[7607 rows x 4 columns]

### 找出名稱包含「資訊」的科系

In [23]:
information = df.loc[
    df["科系名稱"].str.contains(
        "資訊",
        na=False
    ),
    [
        "學校名稱",
        "科系名稱",
        "學生數",
        "教師數",
        "縣市名稱"
    ]
]

print("\n名稱包含「資訊」的科系：")
information

名稱包含「資訊」的科系：

              學校名稱                 科系名稱  學生數  教師數    縣市名稱
90          國立政治大學           (數位)圖書資訊學系   49    0  30 臺北市
91          國立政治大學          圖書資訊與檔案學研究所   12    0  30 臺北市
92          國立政治大學          圖書資訊與檔案學研究所   39    7  30 臺北市
99          國立政治大學  會計(與)(資訊)(科技)(系統)學系   19    0  30 臺北市
100         國立政治大學  會計(與)(資訊)(科技)(系統)學系  133    0  30 臺北市
...            ...                  ...  ...  ...     ...
117835  樹人醫護管理專科學校                資訊管理科  222    7  12 高雄市
117889  聖母醫護管理專科學校                資訊管理科   57    4  02 宜蘭縣
117974      臺北市立大學                資訊科學系   48    0  30 臺北市
117975      臺北市立大學                資訊科學系   73    0  30 臺北市
117976      臺北市立大學                資訊科學系  189   10  30 臺北市

[10177 rows x 5 columns]

### 找出學生人數大於等於 500 人的科系

In [ ]:
### 將學生數轉換成數字
df["學生數"] = pd.to_numeric(
    df["學生數"],
    errors="coerce" # 無法轉換的東西補上NaN
)

large_department = df.loc[
    df["學生數"] >= 500,
    [
        "學校名稱",
        "科系名稱",
        "學生數",
        "教師數",
        "縣市名稱"
    ]
]

print("\n學生人數大於等於 500 人的科系：")
large_department

學生人數大於等於 500 人的科系：

              學校名稱           科系名稱     學生數  教師數    縣市名稱
72          國立政治大學           地政學系   506.0   23  30 臺北市
105         國立政治大學  經營(與)管理(技術)學系   508.0    0  30 臺北市
126         國立政治大學           法律學系   779.0   33  30 臺北市
222         國立清華大學         資訊工程學系   534.0   43  18 新竹市
277         國立臺灣大學         外國語文學系   571.0   83  30 臺北市
...            ...            ...     ...  ...     ...
117892  聖母醫護管理專科學校            護理科   642.0   24  02 宜蘭縣
117902  新生醫護管理專科學校            護理科  3454.0  113  03 桃園市
117903  新生醫護管理專科學校           視光學科   508.0   15  03 桃園市
117910  崇仁醫護管理專科學校            護理科  1962.0   67  10 嘉義縣
117988      臺北市立大學         球類運動學系   542.0   12  30 臺北市

[4263 rows x 5 columns]

### 新增「大型科系」欄位

In [27]:
df["大型科系"] = "否"

df.loc[
    df["學生數"] >= 500,
    "大型科系"
] = "是"

### 保留需要的欄位&修改部分欄位名稱

In [28]:
result = df[
    [
        "學校名稱",
        "科系名稱",
        "日間∕進修別",
        "等級別",
        "學生數",
        "教師數",
        "縣市名稱",
        "大型科系"
    ]
]


### 修改部分欄位名稱
result = result.rename(columns={
    "縣市名稱": "縣市",
    "日間∕進修別": "就讀類型"
})

result

          學校名稱       科系名稱 就讀類型   等級別    學生數  教師數      縣市 大型科系
0       國立政治大學       教育學系  D 日  D 博士   93.0    0  30 臺北市    否
1       國立政治大學       教育學系  D 日  M 碩士   34.0    0  30 臺北市    否
2       國立政治大學       教育學系  D 日  B 學士  250.0   17  30 臺北市    否
3       國立政治大學  華語(文)教學學系  D 日  D 博士   18.0    0  30 臺北市    否
4       國立政治大學  華語(文)教學學系  D 日  M 碩士   55.0    0  30 臺北市    否
...        ...        ...  ...   ...    ...  ...     ...  ...
117995  臺北市立大學   休閒運動管理學系  D 日  M 碩士   33.0    0  30 臺北市    否
117996  臺北市立大學   休閒運動管理學系  N 職  M 碩士   58.0    0  30 臺北市    否
117997  臺北市立大學   休閒運動管理學系  D 日  B 學士  223.0    9  30 臺北市    否
117998  臺北市立大學    通識及共同科目  D 日   NaN    0.0    7  30 臺北市    否
117999  臺北市立大學     師資培育中心  D 日   NaN    0.0    5  30 臺北市    否

[118000 rows x 8 columns]

### 輸出 CSV

In [29]:
result.to_csv(
    "../pandas_output/大專校院科系整理.csv",
    index=False,
    encoding="utf-8-sig"
)

information.to_csv(
    "../pandas_output/資訊相關科系.csv",
    index=False,
    encoding="utf-8-sig"
)