## 下載資料

- [資料來源：高雄市115年不動產買賣實價登錄資料](https://data.gov.tw/dataset/177586?utm_source=chatgpt.com)

In [1]:
import requests
import pandas as pd

### 設定 CSV 資料網址
# 高雄市115年第1季不動產買賣實價登錄資料下載
url = "https://data.kcg.gov.tw/File/DirectDownload/cf41120f-3673-489a-88e8-fc57e2db067f"

headers = {
    "User-Agent": "Mozilla/5.0"
}

### 發送 HTTP 請求
response = requests.get(
    url,
    headers=headers,
    timeout=30
) # 向政府開放資料網站發送 GET 請求

response.raise_for_status() # 如果發生 4xx、5xx 錯誤，直接拋出例外

print("狀態碼：", response.status_code)


### 儲存 CSV
with open("../pandas_datasets/高雄市115年第1季不動產買賣實價登錄資料.csv", "wb") as file:
    file.write(response.content) # 將伺服器回傳的 CSV 原始資料寫入檔案

狀態碼： 200

In [2]:
import requests
import pandas as pd

### 設定 CSV 資料網址

# 高雄市115年第2季不動產買賣實價登錄資料下載
url = "https://data.kcg.gov.tw/File/DirectDownload/b2795896-3bc5-4e48-8693-87fca79708ff"

headers = {
    "User-Agent": "Mozilla/5.0"
}

### 發送 HTTP 請求
response = requests.get(
    url,
    headers=headers,
    timeout=30
) # 向政府開放資料網站發送 GET 請求

response.raise_for_status() # 如果發生 4xx、5xx 錯誤，直接拋出例外

print("狀態碼：", response.status_code)


### 儲存 CSV
with open("../pandas_datasets/高雄市115年第2季不動產買賣實價登錄資料.csv", "wb") as file:
    file.write(response.content) # 將伺服器回傳的 CSV 原始資料寫入檔案

狀態碼： 200

## 讀取資料

In [3]:
import pandas as pd

### 讀取第 1、2 季實價登錄資料
q1_df = pd.read_csv("../pandas_datasets/高雄市115年第1季不動產買賣實價登錄資料.csv")
q2_df = pd.read_csv("../pandas_datasets/高雄市115年第2季不動產買賣實價登錄資料.csv")

### 查看資料筆數
print("第 1 季：", q1_df.shape)
print("第 2 季：", q2_df.shape)

第 1 季： (8255, 38)
第 2 季： (9651, 39)

In [4]:
q1_df.head(1)

,申報種類,交易標的種類,土地數量,建物數量,車位數量,幾房,幾廳,幾衛,有無隔間,建物型態,...,代表地號或門牌,行政區,地段,代表地號,電梯,車位所在樓層,備註欄,主建物面積,附屬建物面積,陽台面積
0,買賣,房地(土地+建物),1,1,0,3,2,1,NaN,華廈(10層含以下有電梯),...,高雄市林園區一心街３號三樓,林園區,港子埔段,NaN,有,NaN,NaN,65.71,0.0,5.48

In [5]:
q2_df.head(1)

,申報種類,交易標的種類,土地數量,建物數量,車位數量,幾房,幾廳,幾衛,有無隔間,建物型態,...,代表地號或門牌,行政區,地段,代表地號,電梯,車位所在樓層,備註欄,主建物面積,附屬建物面積,陽台面積
0,買賣,房地(土地+建物),1,1,0,3,3,2,有,透天厝,...,高雄市左營區店仔頂路６３巷１８弄２０號,左營區,左南段,22980000.0,無,NaN,夾層；,75.98,0.0,0.0

## 合併兩季資料
我們研究的是「115 年目前公布的資料」，所以把 Q1、Q2 接起來。

In [6]:
### 合併第 1、2 季資料
df = pd.concat(
    [q1_df, q2_df],
    ignore_index=True # ignore_index=True 則是重新產生 0、1、2、3... 的 index。
)

print(df.shape)

(17906, 40)

## 認識資料

In [7]:
### 查看資料大小
print(df.shape)

(17906, 40)

In [8]:
### 查看所有欄位
print(df.columns.tolist())

['申報種類', '交易標的種類', '土地數量', '建物數量', '車位數量', '幾房', '幾廳', '幾衛', '有無隔間', '建物型態', '房地總價', '單價元平方公尺', '車位類別', '車位總價', '有無管理組織', '交易日期', '土地移轉面積', '代表地號都市土地使用分區', '代表地號非都市土地使用分區', '代表地號非都市土地使用地', '建物移轉面積', '代表建號主要用途', '代表建號主要建材', '代表建號總層數', '建築完成年月', '代表建號屋齡', '代表建號層次', '車位總持分面積', '代表地號或門牌', '行政區', '地段', '代表地號', '電梯', '車位所在樓層', '備註欄', '主建物面積', '附屬建物面積', '陽台面積', '單價\n元平方公尺', '車位總價格']

In [9]:
### 查看資料型態
print(df.dtypes)

申報種類                 str
交易標的種類               str
土地數量               int64
建物數量               int64
車位數量               int64
幾房                 int64
幾廳                 int64
幾衛                 int64
有無隔間              object
建物型態                 str
房地總價               int64
單價元平方公尺          float64
車位類別                 str
車位總價               int64
有無管理組織               str
交易日期               int64
土地移轉面積           float64
代表地號都市土地使用分區         str
代表地號非都市土地使用分區        str
代表地號非都市土地使用地         str
建物移轉面積           float64
代表建號主要用途             str
代表建號主要建材             str
代表建號總層數              str
建築完成年月           float64
代表建號屋齡           float64
代表建號層次               str
車位總持分面積          float64
代表地號或門牌              str
行政區                  str
地段                   str
代表地號             float64
電梯                   str
車位所在樓層               str
備註欄                  str
主建物面積            float64
附屬建物面積           float64
陽台面積             float64
單價\n元平方公尺        float64
車位總價格            float64
dtype: object

In [10]:
### 查看基本資訊
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17906 entries, 0 to 17905
Data columns (total 40 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   申報種類           17906 non-null  str
 1   交易標的種類         17906 non-null  str
 2   土地數量           17906 non-null  int64
 3   建物數量           17906 non-null  int64
 4   車位數量           17906 non-null  int64
 5   幾房             17906 non-null  int64
 6   幾廳             17906 non-null  int64
 7   幾衛             17906 non-null  int64
 8   有無隔間           9651 non-null   object
 9   建物型態           17906 non-null  str
 10  房地總價           17906 non-null  int64
 11  單價元平方公尺        8191 non-null   float64
 12  車位類別           7994 non-null   str
 13  車位總價           17906 non-null  int64
 14  有無管理組織         17906 non-null  str
 15  交易日期           17906 non-null  int64
 16  土地移轉面積         17906 non-null  float64
 17  代表地號都市土地使用分區   15776 non-null  str
 18  代表地號非都市土地使用分區  1184 non-null   str
 19  代表地號非都市土地使用地   1184 non-null   str
 20  建物移轉面積         17906 non-null  float64
 21  代表建號主要用途       14509 non-null  str
 22  代表建號主要建材       14695 non-null  str
 23  代表建號總層數        14695 non-null  str
 24  建築完成年月         14686 non-null  float64
 25  代表建號屋齡         8341 non-null   float64
 26  代表建號層次         14695 non-null  str
 27  車位總持分面積        17906 non-null  float64
 28  代表地號或門牌        17906 non-null  str
 29  行政區            17906 non-null  str
 30  地段             17388 non-null  str
 31  代表地號           9398 non-null   float64
 32  電梯             17905 non-null  str
 33  車位所在樓層         7976 non-null   str
 34  備註欄            12396 non-null  str
 35  主建物面積          17906 non-null  float64
 36  附屬建物面積         17906 non-null  float64
 37  陽台面積           17906 non-null  float64
 38  單價
元平方公尺       9596 non-null   float64
 39  車位總價格          9651 non-null   float64
dtypes: float64(12), int64(9), object(1), str(18)
memory usage: 5.5+ MB

### 只留下這次會使用的欄位

原始資料欄位很多，但這個問題根本用不到全部。

In [11]:
### 保留這次分析需要的欄位
df_new = df[
    [
        "行政區",
        "交易標的種類",
        "房地總價",
        "單價元平方公尺",
        "建物型態",
        "代表建號屋齡",
        "電梯"
    ]
]

df_new.head()

    行政區     交易標的種類     房地總價  單價元平方公尺           建物型態  代表建號屋齡 電梯
0   林園區  房地(土地+建物)  2500000  28647.0  華廈(10層含以下有電梯)    32.0  有
1   彌陀區         土地  3000000   4155.0             其他     NaN  無
2   岡山區         土地  2660000   4113.0             其他     NaN  無
3  那瑪夏區         土地   300000     84.0             其他     NaN  無
4   茄萣區         土地  1200000  29725.0             其他     NaN  無

### 檢查缺失值

In [12]:
### 統計每個欄位有多少缺失值
df_new.isna().sum()

行政區           0
交易標的種類        0
房地總價          0
單價元平方公尺    9715
建物型態          0
代表建號屋齡     9565
電梯            1
dtype: int64

## 得知「哪個行政區平均單價最高？」

那就需要
```
行政區
單價 元平方公尺
```

因此缺少行政區或單價的資料無法參與這次分析

In [13]:
### 缺少行政區或單價的資料無法參與這次分析
df_new = df.dropna(
    subset=[
        "行政區",
        "單價元平方公尺"
    ]
)
df_new.shape

(8191, 40)

In [14]:
### 計算各行政區平均單價
district_price = (
    df_new
    .groupby("行政區")["單價元平方公尺"]
    .mean()
    .reset_index() # 將行政區從 index 變回一般欄位，同時將結果轉成 DataFrame
)


### 按照平均單價由高到低排序
district_price = district_price.sort_values(
    "單價元平方公尺",
    ascending=False
)

district_price.head()

    行政區        單價元平方公尺
36  鼓山區  116444.941349
11  左營區  105134.350844
13  新興區  102684.700617
4   前金區  100042.339806
5   前鎮區   99794.947761

## 把平方公尺換成「每坪」

政府資料提供的是「單價元平方公尺」，但台灣講房價通常會說坪數。

1 坪約等於 3.305785 平方公尺，因此：

In [15]:
### 將每平方公尺單價換算成每坪單價
district_price["單價萬元每坪"] = (
    district_price["單價元平方公尺"]
    * 3.305785
    / 10000
)
district_price.head()

    行政區        單價元平方公尺     單價萬元每坪
36  鼓山區  116444.941349  38.494194
11  左營區  105134.350844  34.755156
13  新興區  102684.700617  33.945354
4   前金區  100042.339806  33.071847
5   前鎮區   99794.947761  32.990064

## 如果只想拿第一名：

In [18]:
### 找出平均單價最高的行政區
highest_district = district_price.iloc[0]["行政區"]
highest_price = district_price.iloc[0]["單價萬元每坪"]

print("平均單價最高行政區：", highest_district)
print("平均單價：", round(highest_price, 2), "萬元/坪")

平均單價最高行政區： 鼓山區
平均單價： 38.49 萬元/坪