# 高雄哪一區旅館最多

## 下載CSV

- [高雄市一般旅館資料(更新至112年6月30日)](https://data.gov.tw/dataset/47018?utm_source=chatgpt.com)

In [1]:
import requests
import pandas as pd

### 設定 CSV 資料網址
# 高雄市一般旅館資料
url = "https://data.kcg.gov.tw/File/DirectDownload/59e24315-4e78-4455-af5e-8c457600f286"

headers = {
    "User-Agent": "Mozilla/5.0"
}

### 發送 HTTP 請求
response = requests.get(
    url,
    headers=headers,
    timeout=30
) # 向政府開放資料網站發送 GET 請求

response.raise_for_status() # 如果發生 4xx、5xx 錯誤，直接拋出例外

print("狀態碼：", response.status_code)


### 儲存 CSV
with open("../pandas_datasets/高雄市一般旅館資料.csv", "wb") as file:
    file.write(response.content) # 將伺服器回傳的 CSV 原始資料寫入檔案

狀態碼： 200

## 讀取 CSV

In [3]:
import pandas as pd

### 讀取高雄市一般旅館資料
df = pd.read_csv("../pandas_datasets/高雄市一般旅館資料.csv")

### 查看前 5 筆資料
df.head()

,Seq,序號,類別,星等,旅宿名稱,縣市,鄉鎮,地址,電話,傳真,房間數,電子郵件,網址,郵遞區號,經度Lng,緯度Lat,資料序號Seq
0,1,1,國際觀光旅館,五星級,漢來大飯店,高雄市,前金區,高雄市前金區成功一路266號1樓、2樓、10-13樓、15-19樓、22-42樓,07-2161766,07-2161966,540,service@grand-hilai.com,http://www.grand-hilai.com,NaN,120.295946,22.619421,1
1,2,2,國際觀光旅館,NaN,高雄萬豪酒店,高雄市,鼓山區,高雄市鼓山區龍德新路222號,07-5599111,07-5588566,700,info@khhmarriott.com,https://www.marriott.com/hotels/travel/khhmc-k...,NaN,120.306288,22.654565,2
2,3,3,一般觀光旅館,NaN,福容大飯店 高雄,高雄市,鹽埕區,高雄市鹽埕區高雄市鹽埕區五福四路45號,07-5511188,07-5211166,250,rsvn_kh@fullon-hotels.com.tw,http://www.fullon-hotels.com.tw/kh/,NaN,120.287711,22.621363,3
3,4,4,國際觀光旅館,五星級,寒軒國際大飯店,高雄市,苓雅區,高雄市苓雅區四維三路33號,07-332,07-336,311,finance@hanhsien.com.tw,http://www.han-hsien.com.tw,NaN,120.310878,22.619163,4
4,5,5,國際觀光旅館,五星級,高雄福華大飯店,高雄市,新興區,高雄市新興區七賢一路311號,07-2362323,07-2358383,271,jerry-ks@howard-hotels.com.tw,http://kaohsiung.howard-hotels.com.tw/,NaN,120.308190,22.634004,5

In [4]:
### 查看資料大小
df.shape

(372, 17)

In [5]:
### 查看所有欄位
df.columns.tolist()

['Seq',
 '序號',
 '類別',
 '星等',
 '旅宿名稱',
 '縣市',
 '鄉鎮',
 '地址',
 '電話',
 '傳真',
 '房間數',
 '電子郵件',
 '網址',
 '郵遞區號',
 '經度Lng',
 '緯度Lat',
 '資料序號Seq']

In [7]:
### 查看各欄位資料型態
df.dtypes

Seq          int64
序號           int64
類別             str
星等             str
旅宿名稱           str
縣市             str
鄉鎮             str
地址             str
電話             str
傳真             str
房間數          int64
電子郵件           str
網址             str
郵遞區號       float64
經度Lng      float64
緯度Lat      float64
資料序號Seq      int64
dtype: object

In [8]:
### 查看 DataFrame 基本資訊
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 17 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Seq      372 non-null    int64
 1   序號       372 non-null    int64
 2   類別       372 non-null    str
 3   星等       37 non-null     str
 4   旅宿名稱     372 non-null    str
 5   縣市       372 non-null    str
 6   鄉鎮       372 non-null    str
 7   地址       372 non-null    str
 8   電話       372 non-null    str
 9   傳真       372 non-null    str
 10  房間數      372 non-null    int64
 11  電子郵件     272 non-null    str
 12  網址       155 non-null    str
 13  郵遞區號     362 non-null    float64
 14  經度Lng    372 non-null    float64
 15  緯度Lat    372 non-null    float64
 16  資料序號Seq  372 non-null    int64
dtypes: float64(3), int64(4), str(10)
memory usage: 49.5 KB

## 保留分析需要的欄位
這份資料欄位很多，但我們目前只研究住宿市場，所以不用全部留下。

| 欄位     | 用途       |
| ------ | -------- |
| `旅宿名稱` | 辨認是哪間旅館  |
| `星等`   | 後面比較星級旅館 |
| `鄉鎮`   | 行政區分組    |
| `地址`   | 檢查旅館位置   |
| `房間數`  | 分析住宿供給量  |

In [10]:
### 保留這次分析需要的欄位
df_new = df[
    ["旅宿名稱","星等","鄉鎮","地址","房間數"]
].copy()

df_new

         旅宿名稱   星等   鄉鎮                                        地址  房間數
0       漢來大飯店  五星級  前金區  高雄市前金區成功一路266號1樓、2樓、10-13樓、15-19樓、22-42樓  540
1      高雄萬豪酒店  NaN  鼓山區                            高雄市鼓山區龍德新路222號  700
2    福容大飯店 高雄  NaN  鹽埕區                       高雄市鹽埕區高雄市鹽埕區五福四路45號  250
3     寒軒國際大飯店  五星級  苓雅區                             高雄市苓雅區四維三路33號  311
4     高雄福華大飯店  五星級  新興區                            高雄市新興區七賢一路311號  271
..        ...  ...  ...                                       ...  ...
367     適達星旅店  NaN  新興區                 800高雄市新興區南華橫一路14號1樓,夾層,2樓    4
368     長興大旅社  NaN  湖內區                        829高雄市湖內區中正路二段551號    3
369     敲敲門青旅  NaN  三民區                        807高雄市三民區察哈爾二街7巷8號    3
370    馥寓蓮潭旅居  NaN  左營區              813高雄市左營區大中二路816、818、820號15樓    3
371    大鳳商務旅館  NaN  大寮區                       831高雄市大寮區鳳林三路357號3樓    1

[372 rows x 5 columns]

## 檢查缺失值

In [12]:
# df_new.isna()
df_new.isna().sum()

旅宿名稱      0
星等      335
鄉鎮        0
地址        0
房間數       0
dtype: int64

## 查看有哪些行政區

In [13]:
df_new["鄉鎮"].unique()

<StringArray>
['前金區', '鼓山區', '鹽埕區', '苓雅區', '新興區', '鳥松區', '前鎮區', '大樹區', '三民區', '小港區', '橋頭區',
 '鳳山區', '左營區', '旗山區', '六龜區', '楠梓區', '旗津區', '田寮區', '岡山區', '仁武區', '大寮區', '湖內區',
 '大社區', '林園區', '甲仙區', '美濃區', '路竹區', '梓官區', '阿蓮區']
Length: 29, dtype: str

### 查看各行政區出現次數

In [17]:
df_new["鄉鎮"].value_counts().reset_index().rename(columns={"count": "旅館數量"})

     鄉鎮  旅館數量
0   新興區    67
1   三民區    60
2   前金區    39
3   苓雅區    38
4   鳳山區    28
5   鹽埕區    20
6   左營區    18
7   前鎮區    15
8   鼓山區    14
9   楠梓區    10
10  小港區     8
11  岡山區     7
12  湖內區     7
13  大樹區     5
14  旗山區     5
15  大寮區     5
16  仁武區     4
17  林園區     4
18  鳥松區     3
19  橋頭區     3
20  六龜區     3
21  甲仙區     2
22  旗津區     1
23  田寮區     1
24  大社區     1
25  美濃區     1
26  路竹區     1
27  梓官區     1
28  阿蓮區     1